name: Docker Image CI

on:
  push:
    tags:
    - '*'

jobs:

  build:

    runs-on: ubuntu-latest
    
    env: 
      TAG_NAME: ${{ github.ref_name }}
    
    steps:

      - name: Dump tag name
        run: echo 'Building tag $TAG_NAME'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v2.10.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: rahulbot/news-entity-server:$TAG_NAME
