name: Docker Image - Manual to Latest

on:
  workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      # Free up disk space before build
      - name: Free up disk space
        run: |
          echo "Before cleanup disk space:"
          df -h
          sudo rm -rf /opt/hostedtoolcache
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          echo "After cleanup disk space:"
          df -h

      # Grab code associated trigger
      - name: Checkout Version
        uses: actions/checkout@v3

      # What ref triggered this?
      - name: Dump tag name
        run: echo "Building tag ${GITHUB_REF_NAME}"

      # Setup for cross-platform build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # prep for release via DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      # The main build instructions
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/news-entity-server:latest
          # Use GitHub Actions cache
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Optional: Clean up Docker images after build to free more space if needed
      - name: Clean up Docker images
        if: always()
        run: |
          docker image prune -af
          docker system df
          df -h
